---
- name: provision server
  hosts: all
  user: root

  tasks:
    - name: set hostname
      hostname: name={{ hostname }}

    - name: update installed packages
      apt: upgrade=dist update_cache=yes

    - name: create ghc user
      user: name=ghc generate_ssh_key=yes

    - name: add mongodb key
      apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

    - name: add mongodb repo
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present

    - name: install server base packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-file
        - apticron
        - build-essential
        - cowsay
        - curl
        - dnsutils
        - emacs24
        - git
        - htop
        - iftop
        - iotop
        - jq
        - mc
        - mongodb-org
        - nginx-extras
        - nodejs
        - ntp
        - pcregrep
        - python-dev
        - python-pip
        - python-virtualenv
        - python3-dev
        - python3-pip
        - rsync
        - silversearcher-ag
        - tig
        - tmux
        - toilet
        - virtualenvwrapper
        - wget
        - zsh

    - name: set tmp permissions
      file: path=/tmp mode=a+w

    - name: enable agent forwarding
      lineinfile: dest=/etc/ssh/sshd_config
                  state=present
                  regexp='^AllowAgentForwarding'
                  line='AllowAgentForwarding yes'
      notify: restart sshd

    - name: configure ssh keys for root
      authorized_key: user=root key=https://github.com/hut8.keys

    - name: configure ssh keys for ghc
      authorized_key: user=ghc key=https://github.com/hut8.keys

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

- name: make swapfile
  user: root
  hosts: all
  roles:
    - { role: kamaln7.swapfile, swapfile_use_dd: True, swapfile_size: 2048 }

- name: make archive and application directory structures
  user: root
  hosts: all
  tasks:
    - name: root archive
      file: path={{ item }} state=directory owner=ghc
      with_items:
        - /github-archive
        - /github-archive/events
        - /github-archive/loaded
        - /github-archive/logs
        - /github-archive/timeline
        - /github-archive/transformed
        - /github-contributions

- name: install application
  user: ghc
  hosts: all
  tasks:
    - name: clone ghc repository
      git: repo=ssh://git@github.com/hut8/github-contributions.git
           dest=/github-contributions

# TODO: Link configs
