---
- name: provision server
  hosts: all
  user: root

  tasks:
    - name: set hostname
      hostname: name={{ hostname }}

    - name: update installed packages
      apt: upgrade=dist update_cache=yes

    - name: create ghc user
      user: name=ghc generate_ssh_key=yes shell=/bin/bash

    - name: add mongodb key
      apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

    - name: add mongodb repo
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present

    - name: install server base packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - apt-file
        - apticron
        - build-essential
        - cowsay
        - curl
        - dnsutils
        - emacs24
        - git
        - htop
        - iftop
        - iotop
        - jq
        - mc
        - mongodb-org
        - nginx-extras
        - nodejs
        - ntp
        - pcregrep
        - python-dev
        - python-pip
        - python-virtualenv
        - python3-dev
        - python3-pip
        - rsync
        - silversearcher-ag
        - tig
        - tmux
        - toilet
        - virtualenvwrapper
        - wget
        - zsh

    - name: set tmp permissions
      file: path=/tmp mode=a+w

    - name: enable agent forwarding
      lineinfile: dest=/etc/ssh/sshd_config
                  state=present
                  regexp='^AllowAgentForwarding'
                  line='AllowAgentForwarding yes'
      notify: restart sshd

    - name: configure ssh keys for root
      authorized_key: user=root key=https://github.com/hut8.keys

    - name: configure ssh keys for ghc
      authorized_key: user=ghc key=https://github.com/hut8.keys

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

- name: make swapfile
  user: root
  hosts: all
  roles:
    - { role: kamaln7.swapfile, swapfile_use_dd: True, swapfile_size: 2048 }

- name: configure nginx
  user: root
  hosts: all
  tasks:
    - name: uninstall default site config
      file: path=/etc/nginx/sites-enabled/default
            state=absent

    - name: install nginx.conf
      template: src=github-contributions.nginx.conf
                dest=/etc/nginx/sites-enabled/github-contributions.nginx.conf
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

- name: make archive and application directory structures
  user: root
  hosts: all
  tasks:
    - name: root archive
      file: path={{ item }} state=directory owner=ghc group=ghc
      with_items:
        - /github-archive
        - /github-archive/events
        - /github-archive/loaded
        - /github-archive/logs
        - /github-archive/timeline
        - /github-archive/transformed
        - /github-contributions

    - name: fix permissions on /srv
      file: path=/srv owner=ghc group=www-data

- name: install uwsgi configuration
  user: root
  hosts: all
  tasks:
    - name: make uwsgi config directory structure
      file: path={{ item }} state=directory owner=root group=root
      with_items:
        - /etc/uwsgi
        - /etc/uwsgi/vassals

    - name: install uwsgi emperor configuration
      template: src=emperor.ini
                dest=/etc/uwsgi/emperor.ini

    - name: install uwsgi upstart script
      template: src=uwsgi.conf
                dest=/etc/init/uwsgi.conf
      notify: reload upstart

  handlers:
    - name: reload upstart
      shell: initctl reload-configuration

- name: deploy application
  user: ghc
  hosts: all
  tasks:
    - name: pull ghc repository
      git: repo=ssh://git@github.com/hut8/github-contributions.git
           dest=/github-contributions
           accept_hostkey=yes

    - name: identify release
      command: git rev-parse --short HEAD
      register: current_commit
      args:
        chdir: /github-contributions

    - debug: msg="deploying ghc at {{ current_commit.stdout }}"

    - name: install dependencies
      pip: requirements=/github-contributions/requirements.txt
           virtualenv=/srv/venv-{{ current_commit.stdout }}
           virtualenv_command="virtualenv --python=/usr/bin/python3"
           #virtualenv_python=/usr/bin/python3 FIXME with Ansible 2.0

    - name: commit venv
      file: path=/srv/venv
            src=/srv/venv-{{ current_commit.stdout }}
            state=link

    - name: commit app
      file: path=/srv/app
            src=/github-contributions/app
            state=link

- name: set service states
  user: root
  hosts: all
  tasks:
    - name: ensure uwsgi is running
      service: name=uwsgi state=started
